# Generated by Django 4.2.17 on 2024-12-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ollama_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycontent',
            name='propertyId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertyreview',
            name='propertyId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertysummary',
            name='propertyId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
