version: '3.8'

services:
  django:
    build: .
    container_name: django_container
    volumes:
      - .:/app
    networks:
      - ollama_network
      - scrapy_v2_app_network
    environment:
      - DB_NAME=scrapy_db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    command: sh -c "wait-for-it db:5432 -- python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"  # Exposes port 8000 for the Django app

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    restart: unless-stopped
    command: serve
    networks:
      - ollama_network
      - scrapy_v2_app_network

volumes:
  ollama_data:

networks:
  ollama_network:
    driver: bridge
  scrapy_v2_app_network:
    external: true
